# Generated by Django 5.0.1 on 2024-01-17 21:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.IntegerField()),
                ('owner_name', models.CharField(max_length=255)),
                ('account_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='savingsAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.IntegerField()),
                ('owner_name', models.CharField(max_length=255)),
                ('account_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='accountHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('current_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.currentaccount')),
                ('savings_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.savingsaccount')),
            ],
        ),
    ]
